import { IUser } from '../../../../main/ets/common/types/User.type'

export const existingUsers: Array<IUser> = [
  {
    id: 1,
    email: 'gamejoye@gmail.com',
    username: 'gamejoye',
    avatarUrl: 'https://avatars.githubusercontent.com/u/88575063?v=4',
    description: '如果有天樱花再开',
    createTime: '2024-03-29 15:52:40',
  },
  {
    id: 2,
    email: 'mikasa@gmail.com',
    username: 'mikasa',
    avatarUrl: 'https://gamejoye.top/static/media/hg.93ec2beb1dc1340c3791.jpeg',
    description: 'welcome to the world',
    createTime: '2024-03-29 15:53:26',
  },
  {
    id: 3,
    email: 'sakura@gmail.com',
    username: 'sakura',
    avatarUrl: 'https://avatars.githubusercontent.com/u/88575063?v=4',
    description: 'i like sakura',
    createTime: '2024-03-29 15:54:55',
  },
]